### ASSETS REQUESTS

# @name createAsset
POST http://localhost:3333/assets
Content-Type: application/json

{
  "name": "Amazon",
  "ticker": "AMZN",
  "price": 321,
  "image": "AMZN.png"
}

###
@assetId = {{ createAsset.response.body._id }}

######################################
GET http://localhost:3333/assets 

######################################
GET http://localhost:3333/assets/AMZN

### WALLETS REQUESTS

# @name createWallet
POST http://localhost:3333/wallets

###
@walletId = {{ createWallet.response.body._id }}

######################################
GET http://localhost:3333/wallets 

######################################
GET http://localhost:3333/wallets/{{walletId}}

######################################
POST http://localhost:3333/wallets/{{walletId}}/assets
Content-Type: application/json

{
  "assetId": "{{assetId}}",
  "shares": 21
}

### ORDERS REQUESTS

# @name createOrder
POST http://localhost:3333/orders
Content-Type: application/json

{
  "walletId": "{{walletId}}",
  "assetId": "{{assetId}}",
  "shares": 21,
  "type": "BUY",
  "price": 100
}

###
@orderId = {{ createOrder.response.body._id }}

######################################
GET http://localhost:3333/orders?walletId={{walletId}}

######################################
GET http://localhost:3333/orders/{{{{orderId}}}}
